<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $controller->getTitle(); ?></title>
    <script src="/js/Ajax.js" defer></script>
    <script src="/js/NumbersComponent.js" defer></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<div class="application">
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h2 class="text-center">Counter web application</h2>
                <?php if (empty($user)): ?>
                    <form method="POST" action="<?= \Core\Helper\Url::build(); ?>">
                        <div class="form-group">
                            <label for="username">Name</label>
                            <input type="text" class="form-control" id="username" name="username"
                                <?php if (!empty($username)): ?>value="<?= $username; ?>"<?php endif; ?> placeholder="Enter your name">
                        </div>
                        <div class="form-group mt-2">
                            <label for="password">Password</label>
                            <input type="password" class="form-control <?= !empty($error) ? 'is-invalid' : '' ?>"
                                   id="password" name="password" placeholder="Enter your password">
                            <?php if (!empty($error)): ?>
                                <div class="invalid-feedback">
                                    <?= $error; ?>
                                </div>
                            <?php endif ?>
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Enter</button>
                    </form>
                <?php else: ?>
                    <div class="numbers_component container mt-5">
                        <div class="row">
                            <div class="numbers_component_number col text-center fs-1">
                                <?= $user->getNumber(); ?>
                            </div>
                        </div>

                        <div class="row mt-3">
                            <div class="col text-center">
                                <button type="button" class="numbers_component_button btn btn-primary btn-block"
                                        data-url="<?= \Core\Helper\Url::build('ajax', 'add') ?>">+1
                                </button>
                            </div>
                            <div class="col text-center">
                                <a href="<?= \Core\Helper\Url::build('index', 'logout') ?>"
                                   class="btn btn-secondary btn-block">Exit</a>
                            </div>
                        </div>
                    </div>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>
</body>
</html>